/*#ifndef my_asn1_module
#define my_asn1_module*/
#include "cms_mess.h"
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/asn1_mac.h>

ASN1_SEQUENCE(PSMFile) = {
	ASN1_SIMPLE(PSMFile,name,ASN1_UTF8STRING),
	ASN1_SIMPLE(PSMFile,file,ASN1_OCTET_STRING)
}ASN1_SEQUENCE_END(PSMFile);

ASN1_SEQUENCE(PSMCommand) = {
			ASN1_SIMPLE(PSMCommand, command, ASN1_INTEGER),
	    ASN1_OPT(PSMCommand, refseqno, ASN1_INTEGER),
			ASN1_SIMPLE(PSMCommand,text,ASN1_UTF8STRING)
}ASN1_SEQUENCE_END(PSMCommand);

ASN1_SEQUENCE(PSMText) = {
			ASN1_SEQUENCE_OF(PSMText,text,ASN1_UTF8STRING)
}ASN1_SEQUENCE_END(PSMText);

ASN1_ADB_TEMPLATE(psec_default)=ASN1_EXP(PSEC_MESSAGE,d.other,ASN1_ANY,0);

ASN1_ADB(PSEC_MESSAGE) = {
	ADB_ENTRY(NID_psm_comm, ASN1_IMP(PSEC_MESSAGE, d.psmcomm, PSMCommand,0)), 
	ADB_ENTRY(NID_psm_file , ASN1_IMP(PSEC_MESSAGE,d.file,PSMFile,0)),
	ADB_ENTRY(NID_psm_text , ASN1_IMP(PSEC_MESSAGE,d.text,PSMText,0))
}ASN1_ADB_END(PSEC_MESSAGE, 0, mtype, 0, &psec_default_tt, NULL);

ASN1_SEQUENCE(PSEC_MESSAGE) = {
	    ASN1_SIMPLE(PSEC_MESSAGE, mtype, ASN1_OBJECT),
	    ASN1_ADB_OBJECT(PSEC_MESSAGE),
			ASN1_OPT(PSEC_MESSAGE, seqno, ASN1_INTEGER)
}ASN1_SEQUENCE_END(PSEC_MESSAGE);

//DECLARE_ASN1_FUNCTIONS(PSEC_MESSAGE)
IMPLEMENT_ASN1_FUNCTIONS(PSEC_MESSAGE)
//DECLARE_ASN1_FUNCTIONS(PSMFile)
IMPLEMENT_ASN1_FUNCTIONS(PSMText)
//DECLARE_ASN1_FUNCTIONS(PSMCommand)
//IMPLEMENT_ASN1_FUNCTIONS(PSMCommand)
//#endif
